force-app/main/default/objects/Invitation__c/Invitation__c.object-meta.xml
<CustomObject>
    <description>This object is used in invitation app</description>
    <label>Invitation</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Invitation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invitation__c/fields/Event_Address__c.field-meta.xml
<CustomField>
    <fullName>Event_Address__c</fullName>
    <label>Event Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Event_Date_And_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Date_And_Time__c</fullName>
    <label>Event Date and Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Event_Introduction__c.field-meta.xml
<CustomField>
    <fullName>Event_Introduction__c</fullName>
    <label>Event Introduction</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Event_Map_URL__c.field-meta.xml
<CustomField>
    <fullName>Event_Map_URL__c</fullName>
    <label>Event Map URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Event_Participants__c.field-meta.xml
<CustomField>
    <fullName>Event_Participants__c</fullName>
    <label>Event Participants</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Greeting_Message__c.field-meta.xml
<CustomField>
    <fullName>Greeting_Message__c</fullName>
    <label>Greeting Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Instagram_Url__c.field-meta.xml
<CustomField>
    <fullName>Instagram_Url__c</fullName>
    <label>Instagram Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Invite_URL__c.field-meta.xml
<CustomField>
    <fullName>Invite_URL__c</fullName>
    <formula>HYPERLINK(&apos;https://saas-page-2781-dev-ed.scratch.my.site.com/?invitationid=&apos;+ Id , &apos;Invitation Url&apos;, &apos;_blank&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invite URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Respond_By__c.field-meta.xml
<CustomField>
    <fullName>Respond_By__c</fullName>
    <label>Respond By</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Rsvp_Accept_Message__c.field-meta.xml
<CustomField>
    <fullName>Rsvp_Accept_Message__c</fullName>
    <label>Rsvp Accept Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Rsvp_after_date_Message__c.field-meta.xml
<CustomField>
    <fullName>Rsvp_after_date_Message__c</fullName>
    <label>Rsvp after date Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Rsvp_Decline_Message__c.field-meta.xml
<CustomField>
    <fullName>Rsvp_Decline_Message__c</fullName>
    <label>Rsvp Decline Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <label>Theme</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>theme1</fullName>
                <default>true</default>
                <label>theme1</label>
            </value>
            <value>
                <fullName>theme2</fullName>
            </value>
            <value>
                <fullName>theme3</fullName>
            </value>
            <value>
                <fullName>theme4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Twitter_Url__c.field-meta.xml
<CustomField>
    <fullName>Twitter_Url__c</fullName>
    <label>Twitter Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invitation_Response__c/Invitation_Response__c.object-meta.xml
<CustomObject>
    <label>Invitation Response</label>
    <nameField>
        <displayFormat>IR-{0000}</displayFormat>
        <label>Invitation Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invitation Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invitation_Response__c/fields/Additional_comments__c.field-meta.xml
<CustomField>
    <fullName>Additional_comments__c</fullName>
    <label>Additional comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Invitation_Response__c/fields/Invitation__c.field-meta.xml
<CustomField>
    <fullName>Invitation__c</fullName>
    <label>Invitation</label>
    <referenceTo>Invitation__c</referenceTo>
    <relationshipLabel>Invitation Responses</relationshipLabel>
    <relationshipName>Invitation_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invitation_Response__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Joyfully Accept</fullName>
            </value>
            <value>
                <fullName>Regretfully Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Detail__c/Program_Detail__c.object-meta.xml
<CustomObject>
    <label>Program Detail</label>
    <nameField>
        <label>Program Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Detail__c/fields/Invitation__c.field-meta.xml
<CustomField>
    <fullName>Invitation__c</fullName>
    <label>Invitation</label>
    <referenceTo>Invitation__c</referenceTo>
    <relationshipLabel>Program Details</relationshipLabel>
    <relationshipName>Program_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Detail__c/fields/Program_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Date__c</fullName>
    <label>Program Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Detail__c/fields/Program_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Program_End_Time__c</fullName>
    <label>Program End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Program_Detail__c/fields/Program_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Program_Start_Time__c</fullName>
    <label>Program Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/InvitationController.cls
/**
 * @description       : 
 * @author            : Hanna Makhovska
 * @group             : 
 * @last modified on  : 07-01-2024
 * @last modified by  : Hanna Makhovska
**/
public without sharing class InvitationController {
    
    //get Invintation details by Id
    @AuraEnabled(cacheable=true)
    public static Invitation__c getInvitationDetailsById(String Id) {
        try{
            return [SELECT Id, Name, Event_Address__c, Event_Date_And_Time__c, Theme__c, Instagram_Url__c, Twitter_Url__c, Facebook_Url__c, 
            Greeting_Message__c, Event_Introduction__c, Invite_URL__c, Event_Participants__c FROM Invitation__c WHERE Id= :Id ];
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    //get program details by Invitation Id
    @AuraEnabled(cacheable=true)
    public static List<Program_Detail__c> getProgramDetailsByInvitationId(String InvitationId) {
        try{
            return [SELECT Id, Program_Date__c, Program_End_Time__c, Program_Start_Time__c, Name  FROM Program_Detail__c WHERE Invitation__c= :InvitationId ];
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    //get Invintation address by Id
    @AuraEnabled(cacheable=true)
    public static Invitation__c getInvitationAddressById(String Id) {
        try{
            return [SELECT Id, Event_Address__c, Event_Map_URL__c, Contact_Number__c FROM Invitation__c WHERE Id= :Id ];
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    //get RSVP details by Id
    @AuraEnabled(cacheable=true)
    public static Invitation__c getRSVPDetails(String Id) {
        try{
            return [SELECT Id, Rsvp_Accept_Message__c, Rsvp_after_date_Message__c, Rsvp_Decline_Message__c, Respond_By__c FROM Invitation__c WHERE Id= :Id ];
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    //get Response picklist values
    @AuraEnabled(cacheable=true)
    public static List<String> getResponsePicklistValues(){
        //retreive the picklist values
        List<String> picklistValues = new List<String>();
        for(Schema.PicklistEntry picklistEntry:Invitation_Response__c.Response__c.getDescribe().getPicklistValues()){
            picklistValues.add(picklistEntry.getValue());
        }
        return picklistValues;
    }

    //Submit invitation Response
    @AuraEnabled
    public static Boolean submitResponse(Id InvitationId, String Name, String Email, String Phone, String Response, String additionalGuests, String additionalComment) {
        try{
            if(InvitationId != null){
                Invitation_Response__c responseRecord = new Invitation_Response__c(
                    Invitation__c = InvitationId,
                    Name__c = Name,
                    Email__c = Email,
                    Phone__c = Phone,
                    Response__c = Response,
                    Number_of_additional_Guests__c = Decimal.valueOf(additionalGuests),
                    Additional_comments__c = additionalComment
                );
                insert responseRecord;
                return true;
            }
            return false;
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
}