force-app/main/default/objects/Solutions_Log__c/Solutions_Log__c.object-meta.xml
<CustomObject>
    <description>Logs  for all event Info, Error</description>
    <label>Solutions Log</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Solutions Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solutions Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solutions_Log__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>For Batch Logs, contains info: totalObservationSize, totalProductsSize, totalNotPreparedEmailsSize, totalPreparedEmailsSize, batchInfoList, emailsResult</description>
    <label>Body</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Classes__c.field-meta.xml
<CustomField>
    <fullName>Classes__c</fullName>
    <description>Classes where the event(error) occurs</description>
    <label>Classes</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>comment regarding problem solving</description>
    <label>Comment</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <description>Method line where the event (error) occurs</description>
    <label>Line</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message of the event(error)</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Method where the event(error) occurs</description>
    <label>Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>problem priority</description>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>problem solving state</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Watching</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type development log</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>BATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataAccessor.cls
/**
 * @description       : 
 * @author            : Hanna Makhovska
 * @group             : 
 * @last modified on  : 05-16-2024
 * @last modified by  : Hanna Makhovska
**/
public with sharing class DataAccessor {

    public static List<Solutions_Log__c> getSolutionLogs(String typeLog, String status, String priority, String timeLine, DateTime startDateVal, DateTime stopDateVal){
 
        String query = 'SELECT Classes__c, Comment__c, Line__c, Message__c, Method__c, Priority__c, Status__c, Type__c, CreatedDate, Body__c  '+
                'FROM Solutions_Log__c '+
                'WHERE Type__c = \''+String.escapeSingleQuotes(typeLog)+'\' ';
        if(status != '') {
            query += ' AND Status__c = \''+String.escapeSingleQuotes(status)+'\' ';
        }
        if(priority != '') {
            query += ' AND Priority__c = \''+String.escapeSingleQuotes(priority)+'\' ';
        }
        if(timeLine == 'Today') {
            query += ' AND CreatedDate = TODAY ';
        }else if(timeLine == 'Week'){
            query += ' AND CreatedDate >= LAST_WEEK ';
        }else if(timeLine == 'Month'){
            query += ' AND CreatedDate >= LAST_MONTH ';
        }
        if(startDateVal != null && stopDateVal != null){
            query += ' AND CreatedDate >= '+startDateVal.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'')+
                     ' AND CreatedDate <= '+stopDateVal.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'')+' ';
        }
        query += 'ORDER BY CreatedDate DESC LIMIT 50000';
        System.debug(query);
        return  DataAccessorHelper.getDataFromOrg(query);
    }
 
 
    public static List<Solutions_Log__c> getLogItem(Id logId){
        return DataAccessorHelper.getDataFromOrg(
                        'SELECT  Classes__c, Comment__c, Line__c, Message__c, Method__c, Priority__c, Status__c, Type__c, CreatedDate, Body__c '+
                        'FROM Solutions_Log__c '+
                        'WHERE Id = \''+String.escapeSingleQuotes(logId)+'\' '+
                        'LIMIT 1');
    }
}