force-app/main/default/objects/Solutions_Log__c/Solutions_Log__c.object-meta.xml
<CustomObject>
    <description>Logs  for all event Info, Error</description>
    <label>Solutions Log</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Solutions Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solutions Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solutions_Log__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>problem priority</description>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>problem solving state</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Watching</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SolutionLogController.cls
/**
 * @description       : 
 * @author            : Hanna Makhovska
 * @group             : 
 * @last modified on  : 05-16-2024
 * @last modified by  : Hanna Makhovska
**/
public without sharing class SolutionLogController {
    @AuraEnabled /*(cacheable=true)*/
	public static  List<Solutions_Log__c> getLogsData(String typeLog, String status, String priority, String timeLine, String startDate, String stopDate) {
		List<Solutions_Log__c> logsList = new List<Solutions_Log__c>();
		Date startDateVal = null, stopDateVal = null;
		DateTime startDateValDT = null, stopDateValDT = null;
		if(timeLine != ''){
			logsList = DataAccessor.getSolutionLogs(typeLog, status, priority, timeLine, startDateValDT, stopDateValDT);
		} else {
			try {
				startDateVal = Date.valueOf(startDate);
				stopDateVal = Date.valueOf(stopDate);
				startDateValDT = Date.valueOf(startDateVal);
				//stopDateValDT = Date.valueOf(stopDateVal);
				stopDateValDT = DateTime.newInstanceGmt(stopDateVal, Time.newInstance(23,59,59,0));
				logsList = DataAccessor.getSolutionLogs(typeLog, status, priority, timeLine,  startDateValDT, stopDateValDT);
			} catch(Exception e) {
				Utills.createErrorLog('SolutionLogController', 'getLogsData', e.getLineNumber(), e.getMessage() );
				//return logsList;
			}
		}

		return logsList;
	}

	@AuraEnabled
	public static  Solutions_Log__c changeStatusOrPriorityLog(Id recordId, String status, String priority) {
		if(status != null || priority != null){
			List<Solutions_Log__c> logs = DataAccessor.getLogItem(recordId);
			if(!logs.isEmpty()){
				Solutions_Log__c log = logs[0];
					log.Status__c = status != null ? status : log.Status__c;
					log.Priority__c = priority != null ? priority : log.Priority__c;
				try{
					update log;
				}catch(DmlException e){
					Utills.createErrorLog('SolutionLogController', 'changeStatusLog', e.getLineNumber(), e.getMessage() );
					return null;
				}
				return log;
			}
		}
		return null;
	}
}