force-app/main/default/objects/Solutions_Log__c/Solutions_Log__c.object-meta.xml
<CustomObject>
    <description>Logs  for all event Info, Error</description>
    <label>Solutions Log</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Solutions Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solutions Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solutions_Log__c/fields/Classes__c.field-meta.xml
<CustomField>
    <fullName>Classes__c</fullName>
    <description>Classes where the event(error) occurs</description>
    <label>Classes</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Line__c.field-meta.xml
<CustomField>
    <fullName>Line__c</fullName>
    <description>Method line where the event (error) occurs</description>
    <label>Line</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message of the event(error)</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Method where the event(error) occurs</description>
    <label>Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>problem solving state</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Watching</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solutions_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type development log</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>BATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Utills.cls
/**
 * @description       : 
 * @author            : Hanna Makhovska
 * @group             : 
 * @last modified on  : 05-16-2024
 * @last modified by  : Hanna Makhovska
**/
public  class Utills {
    public static Boolean isTriggerExecuted = false;

	/**
	* Method for create an info log.
	* @parameter className - Classes where the event occcurs.
	* @parameter method - Method where the event occcurs.
	* @parameter line - Line where the event occcur.
	* @parameter message - Event message.
	* @parameter type - Event type.
	*/

	
	public static void createLog(String className, String method, Integer line, String message, String type) {
		Solutions_Log__c newLog = new Solutions_Log__c(
				Classes__c = className,
				Method__c = method,
				Line__c = line,
				Message__c = message,
				Type__c = type,
				Status__c = 'New'
		);

		try {

			insert newLog;

		} catch (DmlException exc) {
			/* Can TODO alert email for the Administrator */
			Utills.createConsoleLog('DmlException > Utills.createLog() >>> on line ' + exc.getLineNumber() + ' >>> Error Message: ' + exc.getMessage());
		}
	}

	/**
	* Method for create an error log.
	* @parameter className - Classes where the error occcurs.
	* @parameter method - Method where the error occcurs.
	* @parameter line - Line where the error occcur.
	* @parameter message - Error message.
	*/
	public static void createErrorLog(String className, String method, Integer line, String message) {
		Utills.createLog(className, method, line, message, 'ERROR');
	}

	/**
	* Method for create an info log.
	* @parameter className - Classes where the info occcurs.
	* @parameter method - Method where the info occcurs.
	* @parameter line - Line where the info occcur.
	* @parameter message - Information message.
	*/
	//Not used now
	// public static void createInfoLog(String className, String method, Integer line, String message) {
	//     Utills.createLog(className, method, line, message, 'INFO');
	// }

	public static void createConsoleLog(String message) {
		System.debug(message);
	}

}